force-app/main/default/objects/Dish_Group__c/Dish_Group__c.object-meta.xml
<CustomObject>
    <label>Dish Group</label>
    <nameField>
        <label>Dish Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_Item__c/Dish_Item__c.object-meta.xml
<CustomObject>
    <label>Dish Item</label>
    <nameField>
        <label>Dish Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_Subgroup__c/Dish_Subgroup__c.object-meta.xml
<CustomObject>
    <label>Dish Subgroup</label>
    <nameField>
        <label>Dish Subgroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Subgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_Subgroup__c/fields/Dish_Group__c.field-meta.xml
<CustomField>
    <fullName>Dish_Group__c</fullName>
    <label>Dish Group</label>
    <referenceTo>Dish_Group__c</referenceTo>
    <relationshipLabel>Dish Subgroups</relationshipLabel>
    <relationshipName>Subgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <label>Delivery Address</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
                <default>true</default>
                <label>Ordered</label>
            </value>
            <value>
                <fullName>Assembling</fullName>
            </value>
            <value>
                <fullName>Delivering</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Dish_Item__c.field-meta.xml
<CustomField>
    <fullName>Dish_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dish Item</label>
    <referenceTo>Dish_Item__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/MyOrder__c.field-meta.xml
<CustomField>
    <fullName>MyOrder__c</fullName>
    <label>MyOrder</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_DishItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FetchDataHelper.cls
public with sharing class FetchDataHelper {

    @AuraEnabled(cacheable=true)
    public static List<Dish_Group__c> getGroups(){
        return [SELECT Id, Name 
                FROM Dish_Group__c
                WITH SECURITY_ENFORCED];
    }

    @AuraEnabled(cacheable=true)
    public static List<Dish_Subgroup__c> getSubgroupsByGroup(Id groupId){
        return [SELECT Id, Name
                FROM Dish_Subgroup__c 
                WHERE Dish_Group__c =: groupId
                WITH SECURITY_ENFORCED];
    }

    @AuraEnabled(cacheable=true)
    public static List<Dish_Item__c> getDishesBySubgroup(Id subgroupId){
        return [SELECT Id, Name, Price__c, Description__c, Amount__c
                FROM Dish_Item__c 
                WHERE Dish_Subgroup__c =: subgroupId
                WITH SECURITY_ENFORCED];
    }

    @AuraEnabled(cacheable=true)
    public static List<Order__c> getOrdersById(Id userId){
        return [SELECT Id, Cost__c, Date__c, Status__c, Delivery_Address__c, (SELECT Dish_Item__r.Name, Amount__c FROM Order_Items__r)
                FROM Order__c 
                WHERE OwnerId =: userId
                WITH SECURITY_ENFORCED];
    }

     

    @AuraEnabled
    public static Id insertOrder(Decimal totalPrice, Id owner, String address){
        Order__c order = new Order__c(
            Cost__c = totalPrice,
            OwnerId = owner,
            Delivery_Address__c = address
        );
        try{
            insert order;
            return order.Id;
        } catch(DmlException e) {
            return '0';
        }
    }

    @AuraEnabled
    public static Id insertOrderItem(Integer amount, String comments, String dishItemId, String orderId){
        
            //Id dishItemId = getDishItemIdByName(dishItemName);
            Order_Item__c orderItem = new Order_Item__c(
                Amount__c = amount,
                Comments__c = comments,
                Dish_Item__c = dishItemId,
                MyOrder__c = orderId
            );
            insert orderItem;
            return orderItem.Id;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getPickListValuesIntoList(){
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Order__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
     }
    
}